In [10]:
import pandas as pd

df = pd.read_csv("202608_Despesas.csv", sep=";", encoding="latin-1")
df.head()

,Ano e mês do lançamento,Código Órgão Superior,Nome Órgão Superior,Código Órgão Subordinado,Nome Órgão Subordinado,Código Unidade Gestora,Nome Unidade Gestora,Código Gestão,Nome Gestão,Código Unidade Orçamentária,...,Código Elemento de Despesa,Nome Elemento de Despesa,Código Modalidade da Despesa,Modalidade da Despesa,Valor Empenhado (R$),Valor Liquidado (R$),Valor Pago (R$),Valor Restos a Pagar Inscritos (R$),Valor Restos a Pagar Cancelado (R$),Valor Restos a Pagar Pagos (R$)
0,2026/08,52000.0,Ministério da Defesa,52904.0,Fundo do Exército,167103,50 BATALHAO DE INFANTARIA DE SELVA,1.0,TESOURO NACIONAL,52921,...,39,Outros Serviços de Terceiros - Pessoa Juríd,90,Aplicações Diretas,"349244,54","442936,09","345518,57","0,00","0,00","0,00"
1,2026/08,52000.0,Ministério da Defesa,52111.0,Comando da Aeronáutica,120641,BASE AEREA DE PORTO VELHO,1.0,TESOURO NACIONAL,52111,...,30,Material de Consumo,90,Aplicações Diretas,"23445,27","45740,21","45247,83","0,00","0,00","0,00"
2,2026/08,26000.0,Ministério da Educação,26256.0,Centro Federal de Educação Tecnológica Celso S...,153010,CENTRO FED.DE EDUC.TECNOL.CELSO S.DA FONSECA,15244.0,CENTRO FED.EDUC.TECN.CELSO SUCKOW DA FONSECA,26256,...,37,Locação de Mão-de-Obra,90,Aplicações Diretas,"2335309,22","1386611,75","1833276,69","0,00","0,00","0,00"
3,2026/08,52000.0,Ministério da Defesa,52111.0,Comando da Aeronáutica,120632,GRUPAMENTO DE APOIO DE RECIFE,1.0,TESOURO NACIONAL,52911,...,30,Material de Consumo,90,Aplicações Diretas,"362837,81","132210,62","120499,56","0,00","0,00","0,00"
4,2026/08,26000.0,Ministério da Educação,26420.0,"Instituto Federal de Educação, Ciência e Tecno...",158269,IFFAR - CAMPUS JULIO CASTILHOS,26420.0,"INST.FED.DE EDUC.,CIENC.E TEC.FARROUPILHA",26298,...,32,"Material, Bem ou Serviço para Distribuição",90,Aplicações Diretas,"62962,10","22279,80","18364,82","0,00","0,00","0,00"

In [6]:
df.columns.tolist()

['Ano e mês do lançamento',
 'Código Órgão Superior',
 'Nome Órgão Superior',
 'Código Órgão Subordinado',
 'Nome Órgão Subordinado',
 'Código Unidade Gestora',
 'Nome Unidade Gestora',
 'Código Gestão',
 'Nome Gestão',
 'Código Unidade Orçamentária',
 'Nome Unidade Orçamentária',
 'Código Função',
 'Nome Função',
 'Código Subfução',
 'Nome Subfunção',
 'Código Programa Orçamentário',
 'Nome Programa Orçamentário',
 'Código Ação',
 'Nome Ação',
 'Código Plano Orçamentário',
 'Plano Orçamentário',
 'Código Programa Governo',
 'Nome Programa Governo',
 'UF',
 'Município',
 'Código Subtítulo',
 'Nome Subtítulo',
 'Código Localizador',
 'Nome Localizador',
 'Sigla Localizador',
 'Descrição Complementar Localizador',
 'Código Autor Emenda',
 'Nome Autor Emenda',
 'Código Categoria Econômica',
 'Nome Categoria Econômica',
 'Código Grupo de Despesa',
 'Nome Grupo de Despesa',
 'Código Elemento de Despesa',
 'Nome Elemento de Despesa',
 'Código Modalidade da Despesa',
 'Modalidade da Despesa',
 'Valor Empenhado (R$)',
 'Valor Liquidado (R$)',
 'Valor Pago (R$)',
 'Valor Restos a Pagar Inscritos (R$)',
 'Valor Restos a Pagar Cancelado (R$)',
 'Valor Restos a Pagar Pagos (R$)']

In [12]:
#converted Brazilian format to float
df['Valor Pago (R$)']= (
df['Valor Pago (R$)'].str.replace('.','', regex=False).str.replace(',','.', regex=False).astype(float)
)
df.head()

,Ano e mês do lançamento,Código Órgão Superior,Nome Órgão Superior,Código Órgão Subordinado,Nome Órgão Subordinado,Código Unidade Gestora,Nome Unidade Gestora,Código Gestão,Nome Gestão,Código Unidade Orçamentária,...,Código Elemento de Despesa,Nome Elemento de Despesa,Código Modalidade da Despesa,Modalidade da Despesa,Valor Empenhado (R$),Valor Liquidado (R$),Valor Pago (R$),Valor Restos a Pagar Inscritos (R$),Valor Restos a Pagar Cancelado (R$),Valor Restos a Pagar Pagos (R$)
0,2026/08,52000.0,Ministério da Defesa,52904.0,Fundo do Exército,167103,50 BATALHAO DE INFANTARIA DE SELVA,1.0,TESOURO NACIONAL,52921,...,39,Outros Serviços de Terceiros - Pessoa Juríd,90,Aplicações Diretas,"349244,54","442936,09",345518.57,"0,00","0,00","0,00"
1,2026/08,52000.0,Ministério da Defesa,52111.0,Comando da Aeronáutica,120641,BASE AEREA DE PORTO VELHO,1.0,TESOURO NACIONAL,52111,...,30,Material de Consumo,90,Aplicações Diretas,"23445,27","45740,21",45247.83,"0,00","0,00","0,00"
2,2026/08,26000.0,Ministério da Educação,26256.0,Centro Federal de Educação Tecnológica Celso S...,153010,CENTRO FED.DE EDUC.TECNOL.CELSO S.DA FONSECA,15244.0,CENTRO FED.EDUC.TECN.CELSO SUCKOW DA FONSECA,26256,...,37,Locação de Mão-de-Obra,90,Aplicações Diretas,"2335309,22","1386611,75",1833276.69,"0,00","0,00","0,00"
3,2026/08,52000.0,Ministério da Defesa,52111.0,Comando da Aeronáutica,120632,GRUPAMENTO DE APOIO DE RECIFE,1.0,TESOURO NACIONAL,52911,...,30,Material de Consumo,90,Aplicações Diretas,"362837,81","132210,62",120499.56,"0,00","0,00","0,00"
4,2026/08,26000.0,Ministério da Educação,26420.0,"Instituto Federal de Educação, Ciência e Tecno...",158269,IFFAR - CAMPUS JULIO CASTILHOS,26420.0,"INST.FED.DE EDUC.,CIENC.E TEC.FARROUPILHA",26298,...,32,"Material, Bem ou Serviço para Distribuição",90,Aplicações Diretas,"62962,10","22279,80",18364.82,"0,00","0,00","0,00"

In [13]:
#Question 1 — Top 10 órgãos by amount paid:

df.groupby('Nome Órgão Superior')['Valor Pago (R$)'].sum().sort_values(ascending=False).head(10)

Nome Órgão Superior
Ministério da Fazenda                          4.172662e+11
Ministério da Previdência Social               9.482623e+10
Ministério da Educação                         1.975730e+10
Ministério da Saúde                            1.847058e+10
Ministério do Desenvolvimento e Assistência    1.366965e+10
Ministério do Trabalho e Emprego               1.306211e+10
Ministério de Minas e Energia                  1.257696e+10
Ministério da Defesa                           9.704504e+09
Ministério de Portos e Aeroportos              8.250729e+09
Ministério da Agricultura e Pecuária           6.111753e+09
Name: Valor Pago (R$), dtype: float64

In [14]:
#Question 2 — Total paid per expense group:

df.groupby('Nome Grupo de Despesa')['Valor Pago (R$)'].sum().sort_values(ascending=False)

Nome Grupo de Despesa
Amortização/Refinanciamento da Dívida    2.875933e+11
Outras Despesas Correntes                2.046100e+11
Juros e Encargos da Dívida               8.391064e+10
Pessoal e Encargos Sociais               2.770158e+10
Inversões Financeiras                    2.454212e+10
Investimentos                            2.964107e+09
Name: Valor Pago (R$), dtype: float64

In [15]:
# Question 3 — Duplicate rows:

df.duplicated().sum()

np.int64(0)